# -*- coding: utf-8 -*-
"""tutorial_earth_observation_map_for_kids_trinidad_tobago_edition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/lindangulopez/ae65e6769e7045f490e5d773efd60c74/tutorial_earth_observation_map_for_kids_trinidad_tobago_edition.ipynb

# 🛰️ Earth Observation Map — Trinidad & Tobago Edition 🇹🇹

Learn how satellites observe Earth from space and help us protect it! 🌍

This fun activity lets you make an **interactive Earth map** — click the red and black dots to explore oceans, forests, volcanoes, weather systems, and more!

---

### 🌟 Step 1: Choose Your Satellite Map

Pick the kind of satellite map you want to explore — Earth in daylight, at night, or with clouds and storms!
"""

import ipywidgets as widgets
from IPython.display import HTML, display

# Caribbean-centered Earth map (NASA Blue Marble)
caribbean_view = "https://eoimages.gsfc.nasa.gov/images/imagerecords/74000/74192/world.topo.bathy.200412.3x5400x2700_caribbean.jpg"

# NASA/Wikimedia map backgrounds
map_options = {
    "🌎 Earth (Caribbean Focus)": caribbean_view,
    "🌍 Earth (Daytime Global)": "https://eoimages.gsfc.nasa.gov/images/imagerecords/79000/79765/earthobserved_vir_2012263_lrg.jpg",
    "🌌 Earth (Night Lights)": "https://eoimages.gsfc.nasa.gov/images/imagerecords/55000/55167/earth_lights_lrg.jpg",
    "☁️ Clouds and Weather": "https://eoimages.gsfc.nasa.gov/images/imagerecords/144000/144311/world.topo.200406.3x5400x2700.jpg"
}

map_dropdown = widgets.Dropdown(
    options=map_options,
    value=caribbean_view,
    description="Choose a map:",
    style={'description_width': 'initial'},
    layout=widgets.Layout(width="70%")
)

display(map_dropdown)



"""### 🗺️ Step 2: Create Your Interactive Map (🇹🇹 Red, Black & White Style)

This step builds your clickable Earth map — in the colors of Trinidad & Tobago’s national flag! 🇹🇹
"""

def make_map(bg_url):
    html_map = f"""
    <link href='//fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Roboto:100,300,400,700,900' rel='stylesheet' type='text/css'>

    <style>
    /* === 🇹🇹 Trinidad & Tobago Theme === */
    body {{
        font-family: 'Roboto', sans-serif;
        background-color: #ffffff;
        text-align: center;
    }}
    h1 {{
        color: #d90429;
    }}
    .description {{
        font-size: 18px;
        color: #000000;
    }}
    .distribution-map {{
        position: relative;
        width: 85%;
        height: 500px;
        margin: 20px auto;
        background-image: url('{bg_url}');
        background-size: cover;
        background-position: center;
        border: 6px solid #000000;
        border-radius: 12px;
        box-shadow: 0 0 20px rgba(217, 4, 41, 0.5);
    }}
    .map-point {{
        position: absolute;
        width: 28px;
        height: 28px;
        background-color: #d90429;
        border: 3px solid #ffffff;
        border-radius: 50%;
        cursor: pointer;
        transition: transform 0.2s, background-color 0.3s;
    }}
    .map-point:hover {{
        transform: scale(1.3);
        background-color: #000000;
        border-color: #d90429;
    }}
    .map-point .content {{
        display: none;
        position: absolute;
        top: -10px;
        left: 30px;
        background: #ffffff;
        border: 2px solid #d90429;
        border-radius: 10px;
        padding: 10px;
        width: 200px;
        text-align: left;
        color: #000000;
        font-size: 14px;
    }}
    .map-point:focus .content,
    .map-point:active .content {{
        display: block;
    }}
    </style>

    <h1>🇹🇹 My Caribbean Earth Observation Map</h1>
    <p class="description">Click the red circles to learn about how satellites watch over our region and planet!</p>

    <div class="distribution-map">
        <!-- Ocean Point -->
        <button class="map-point" style="top:45%;left:35%">
            <div class="content">
                <h2>🌊 Caribbean Sea</h2>
                <p>Satellites track sea color and coral reef health in the Caribbean!</p>
            </div>
        </button>

        <!-- Forests -->
        <button class="map-point" style="top:60%;left:30%">
            <div class="content">
                <h2>🌳 South America</h2>
                <p>Earth satellites monitor the Amazon rainforest to track deforestation.</p>
            </div>
        </button>

        <!-- Volcano -->
        <button class="map-point" style="top:50%;left:25%">
            <div class="content">
                <h2>🌋 Soufrière Volcano</h2>
                <p>Satellites can spot ash plumes and heat from volcanoes in the Lesser Antilles!</p>
            </div>
        </button>

        <!-- Trinidad -->
        <button class="map-point" style="top:70%;left:42%">
            <div class="content">
                <h2>🇹🇹 Trinidad & Tobago</h2>
                <p>From space, satellites can see lush forests, coral reefs, and bright lights during Carnival!</p>
            </div>
        </button>

        <!-- Weather -->
        <button class="map-point" style="top:35%;left:50%">
            <div class="content">
                <h2>🌀 Atlantic Weather</h2>
                <p>Weather satellites track hurricanes forming over the Atlantic Ocean.</p>
            </div>
        </button>
    </div>

    <p class="description">✨ Try choosing another map above, or edit the text to make your own!</p>
    """
    display(HTML(html_map))

# Display the map
make_map(map_dropdown.value)

"""### 🔄 Step 3: Switch Between Maps

Change the dropdown menu above, then **run the cell below** again to refresh your map with a new nightlights background!
"""

make_map(map_dropdown.value)

"""### 🌍 Step 4: Learn & Explore

| Emoji | Topic | What Satellites Do |
|:--:|:--|:--|
| 🌊 | Oceans | Track coral reefs and water quality |
| 🌳 | Forests | Detect deforestation and reforestation |
| 🌋 | Volcanoes | Monitor eruptions and ash clouds |
| 🌀 | Weather | Predict hurricanes and tropical storms |
| 🌃 | Cities | See city lights and energy use |
| 🛰️ | Space | Over 2,000 satellites study Earth today! |

### 🧠 Step 5: Challenge!

#### Make your own interactive map on CodePen: HTML + CSS
"""

from IPython.display import display, HTML

display(HTML('''
<iframe height="300" style="width: 100%;" scrolling="no" title="INTERACTIVE CSS MAP"
src="https://codepen.io/lindangulopez/embed/LEGrwLw?default-tab=html%2Cresult"
frameborder="no" loading="lazy" allowtransparency="true">
  See the Pen <a href="https://codepen.io/lindangulopez/pen/LEGrwLw">
  INTERACTIVE CSS MAP</a> by LINDA ANGULO LOPEZ (<a href="https://codepen.io/lindangulopez">@lindangulopez</a>)
  on <a href="https://codepen.io">CodePen</a>.
</iframe>
'''))

"""## 🔀 Part 1: How to Fork and Edit the CodePen

1. **Open the CodePen link**
   Click the [CodePen link](https://codepen.io/lindangulopez/pen/xbZyYNG)  your teacher gave you. You should see the interactive map on the page.

2. **Sign in or sign up**
   To make your own copy, you need to be logged in. You can use Google or GitHub accounts to log in.

3. **Click “Fork”**
   At the top right of the CodePen page, you’ll see a button called **Fork**. Click it.

   * “Forking” means making your own copy of someone else’s code so you can change it without breaking the original.

4. **Start editing**

   * You’ll see three boxes: **HTML**, **CSS**, and **JS**.

     * HTML is like the skeleton or structure of your page.
     * CSS is how it looks—colors, fonts, and layout.
     * JS (JavaScript) is how it behaves or moves (this code doesn’t really use JS much).

5. **Change the map points**

   * In the HTML box, find the `<button class="map-point" ...>` sections.
   * You can change the text inside `<h2>` and `<p>` to name new places or write funny messages.
   * You can also move the points by changing the `top:` and `left:` percentages. For example:

     ```html
     <button class="map-point" style="top:50%;left:50%">
     ```

     moves that point to the middle of the map.

6. **Change colors or fonts (optional)**

   * In the CSS box, you can change colors by finding things like `background-color:` or `color:`.
   * You can change the font by editing the `link href` at the top, or pick another from Google Fonts.

7. **Save your CodePen**

   * Click **Save** at the top. You now have your own interactive map that you can share!

"""

from IPython.display import display, HTML

display(HTML('''
<iframe height="300" style="width: 100%;" scrolling="no" title="Step 1 : Fork INTERACTIVE CSS MAP"
src="https://codepen.io/lindangulopez/embed/xbZyYNG?default-tab=html%2Cresult"
frameborder="no" loading="lazy" allowtransparency="true">
  See the Pen <a href="https://codepen.io/lindangulopez/pen/xbZyYNG">
  Step 1 : Fork INTERACTIVE CSS MAP</a> by LINDA ANGULO LOPEZ (<a href="https://codepen.io/lindangulopez">@lindangulopez</a>)
  on <a href="https://codepen.io">CodePen</a>.
</iframe>
'''))

"""## 💻 Part 2: Explaining the Code

1. **What this map does**

   * This map is a picture with **clickable points**.
   * When you click a point, it opens a little box with a name and description of a place.

2. **Breaking down the HTML**

   * `<h1>` is the title of your page:

     ```html
     <h1>Pure CSS Interactive Map</h1>
     ```

     → It just shows big letters at the top.

   * `<p>` is a paragraph of text:

     ```html
     <p class="description">Click the points to expand them.</p>
     ```

     → It gives instructions or extra info.

   * `<div class="distribution-map">` is like the **map container**.

     * Inside this, each `<button class="map-point">` is a **dot on the map**.

   * Each button has:

     ```html
     <div class="content">
       <div class="centered-y">
         <h2>Place Name</h2>
         <p>Description</p>
       </div>
     </div>
     ```

     → This is the **popup box** you see when you click the point.

3. **The `style="top:xx%;left:xx%"` part**

   * These numbers decide **where the dot appears** on the map.
   * Top = how far from the top, Left = how far from the left.

4. **Fonts**

   ```html
   <link href='//fonts.googleapis.com/css?family=Roboto' ...>
   ```

   → This just changes how the letters look on your page. Fancy letters!

5. **Clicking works with CSS**

   * Normally, buttons change style when clicked using CSS. That’s what makes the popup boxes appear.

## ✏️ Part 3:Edit the CopePen

* Try changing the text to add data for Trinidad and Tobago locations.
* Experiment with colors in CSS—see what happens!
* Move the map points around with `top` and `left` and watch them jump to new places.

Tip: add this code
```html
    <button class="map-point" style="top:35%;left:20%;">
        <div class="content">
            <div class="centered-y">
                <h2>🛰️TRINIDAD & TOBAGO</h2>
<ol>
  <li><strong>Landsat 8 & 9</strong> → 📸 Take pictures of cities, forests, rivers, and coastlines</li>
  <li><strong>Sentinel-1 & CryoSat-2</strong> → 📡 Radar monitors sea level rise, floods, and land movement</li>
  <li><strong>Sentinel-2, ICESat-2 & Terra/Aqua (MODIS)</strong> → 🌱🔦🌡️ Observe vegetation, water levels, coastal changes, and temperature</li>
</ol>

          </div>
        </div>
    </button>
 ```
"""

from IPython.display import display, HTML

display(HTML('''
<iframe height="300" style="width: 100%;" scrolling="no" title="Step 2 : Edit INTERACTIVE CSS MAP"
src="https://codepen.io/lindangulopez/embed/qEbJojr?default-tab=html%2Cresult"
frameborder="no" loading="lazy" allowtransparency="true">
  See the Pen <a href="https://codepen.io/lindangulopez/pen/qEbJojr">
  Step 2 : Edit INTERACTIVE CSS MAP</a> by LINDA ANGULO LOPEZ (<a href="https://codepen.io/lindangulopez">@lindangulopez</a>)
  on <a href="https://codepen.io">CodePen</a>.
</iframe>
'''))

"""### 👩‍🏫 Teacher Notes

* **Theme:** Trinidad & Tobago colors (Red, Black, White)
* **No file uploads or external data** required
* **Target students:** Ages 8–13, learning about **Earth observation**, **climate**, and **Caribbean geography**
* **Skills taught:** Using developer tools in CodePen — **fork, edit, and publish** projects
* **Compatible with:** **Jupyter Notebook**, **JupyterLab**, and **Google Colab**
"""
