# -*- coding: utf-8 -*-
"""Tutorial_Earth_observation_map_for_kids_trinidad_tobago_edition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eFzGttdLZhY3MvLWVgUnEh9qHE0PG9Yx

# 🛰️ Earth Observation Map — Trinidad & Tobago Edition 🇹🇹

Learn how satellites observe Earth from space and help us protect it! 🌍

This fun activity lets you make an **interactive Earth map** — click the red and black dots to explore oceans, forests, volcanoes, weather systems, and more!

---

### 🌟 Step 1: Choose Your Satellite Map

Pick the kind of satellite map you want to explore — Earth in daylight, at night, or with clouds and storms!
"""

import ipywidgets as widgets
from IPython.display import HTML, display

# Caribbean-centered Earth map (NASA Blue Marble)
caribbean_view = "https://eoimages.gsfc.nasa.gov/images/imagerecords/74000/74192/world.topo.bathy.200412.3x5400x2700_caribbean.jpg"

# NASA/Wikimedia map backgrounds
map_options = {
    "🌎 Earth (Caribbean Focus)": caribbean_view,
    "🌍 Earth (Daytime Global)": "https://eoimages.gsfc.nasa.gov/images/imagerecords/79000/79765/earthobserved_vir_2012263_lrg.jpg",
    "🌌 Earth (Night Lights)": "https://eoimages.gsfc.nasa.gov/images/imagerecords/55000/55167/earth_lights_lrg.jpg",
    "☁️ Clouds and Weather": "https://eoimages.gsfc.nasa.gov/images/imagerecords/144000/144311/world.topo.200406.3x5400x2700.jpg"
}

map_dropdown = widgets.Dropdown(
    options=map_options,
    value=caribbean_view,
    description="Choose a map:",
    style={'description_width': 'initial'},
    layout=widgets.Layout(width="70%")
)

display(map_dropdown)



"""### 🗺️ Step 2: Create Your Interactive Map (🇹🇹 Red, Black & White Style)

This step builds your clickable Earth map — in the colors of Trinidad & Tobago’s national flag! 🇹🇹
"""

def make_map(bg_url):
    html_map = f"""
    <link href='//fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Roboto:100,300,400,700,900' rel='stylesheet' type='text/css'>

    <style>
    /* === 🇹🇹 Trinidad & Tobago Theme === */
    body {{
        font-family: 'Roboto', sans-serif;
        background-color: #ffffff;
        text-align: center;
    }}
    h1 {{
        color: #d90429;
    }}
    .description {{
        font-size: 18px;
        color: #000000;
    }}
    .distribution-map {{
        position: relative;
        width: 85%;
        height: 500px;
        margin: 20px auto;
        background-image: url('{bg_url}');
        background-size: cover;
        background-position: center;
        border: 6px solid #000000;
        border-radius: 12px;
        box-shadow: 0 0 20px rgba(217, 4, 41, 0.5);
    }}
    .map-point {{
        position: absolute;
        width: 28px;
        height: 28px;
        background-color: #d90429;
        border: 3px solid #ffffff;
        border-radius: 50%;
        cursor: pointer;
        transition: transform 0.2s, background-color 0.3s;
    }}
    .map-point:hover {{
        transform: scale(1.3);
        background-color: #000000;
        border-color: #d90429;
    }}
    .map-point .content {{
        display: none;
        position: absolute;
        top: -10px;
        left: 30px;
        background: #ffffff;
        border: 2px solid #d90429;
        border-radius: 10px;
        padding: 10px;
        width: 200px;
        text-align: left;
        color: #000000;
        font-size: 14px;
    }}
    .map-point:focus .content,
    .map-point:active .content {{
        display: block;
    }}
    </style>

    <h1>🇹🇹 My Caribbean Earth Observation Map</h1>
    <p class="description">Click the red circles to learn about how satellites watch over our region and planet!</p>

    <div class="distribution-map">
        <!-- Ocean Point -->
        <button class="map-point" style="top:45%;left:35%">
            <div class="content">
                <h2>🌊 Caribbean Sea</h2>
                <p>Satellites track sea color and coral reef health in the Caribbean!</p>
            </div>
        </button>

        <!-- Forests -->
        <button class="map-point" style="top:60%;left:30%">
            <div class="content">
                <h2>🌳 South America</h2>
                <p>Earth satellites monitor the Amazon rainforest to track deforestation.</p>
            </div>
        </button>

        <!-- Volcano -->
        <button class="map-point" style="top:50%;left:25%">
            <div class="content">
                <h2>🌋 Soufrière Volcano</h2>
                <p>Satellites can spot ash plumes and heat from volcanoes in the Lesser Antilles!</p>
            </div>
        </button>

        <!-- Trinidad -->
        <button class="map-point" style="top:70%;left:42%">
            <div class="content">
                <h2>🇹🇹 Trinidad & Tobago</h2>
                <p>From space, satellites can see lush forests, coral reefs, and bright lights during Carnival!</p>
            </div>
        </button>

        <!-- Weather -->
        <button class="map-point" style="top:35%;left:50%">
            <div class="content">
                <h2>🌀 Atlantic Weather</h2>
                <p>Weather satellites track hurricanes forming over the Atlantic Ocean.</p>
            </div>
        </button>
    </div>

    <p class="description">✨ Try choosing another map above, or edit the text to make your own!</p>
    """
    display(HTML(html_map))

# Display the map
make_map(map_dropdown.value)

"""### 🔄 Step 3: Switch Between Maps

Change the dropdown menu above, then **run the cell below** again to refresh your map with a new nightlights background!
"""

make_map(map_dropdown.value)

"""### 🌍 Step 4: Learn & Explore

| Emoji | Topic | What Satellites Do |
|:--:|:--|:--|
| 🌊 | Oceans | Track coral reefs and water quality |
| 🌳 | Forests | Detect deforestation and reforestation |
| 🌋 | Volcanoes | Monitor eruptions and ash clouds |
| 🌀 | Weather | Predict hurricanes and tropical storms |
| 🌃 | Cities | See city lights and energy use |
| 🛰️ | Space | Over 2,000 satellites study Earth today! |

### 🧠 Step 5: Challenge!

- Add your own red dot for your **town or school in Trinidad or Tobago** 🇹🇹  
- Write what satellites could observe there — maybe the coastline, coral reefs, or forests 🌴  
- Try the **Night Lights** map to see Port of Spain glowing at night! 🌃

### 👩‍🏫 Teacher Notes

- Trinidad & Tobago color theme (Red, Black, White)
- No file uploads or data required
- Uses free NASA imagery
- Great for lessons on **Earth observation**, **climate**, and **Caribbean geography**
- Works in **Jupyter**, **JupyterLab**, and **Google Colab**
"""